# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8008
  connection-timeout: 5000ms
#  servlet:
#    context-path: /search

spring:
  # 环境 dev|test|prod
#  profiles:
#    active: dev
#  # jackson时间格式化

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.16.221:8848
  application:
    name: storeTemplate.search
  thymeleaf:
    cache: false
