spring:
  cloud:
    gateway:
      routes:
        #        - id: test_route
        #          uri: https://www.baidu.com
        #          predicates:
        #            - Query=url,baidu
        #
        #        - id: qq_route
        #          uri: https://www.qq.com
        #          predicates:
        #            - Query=url,qq
        - id: after_route
          uri: https://www.qq.com
          predicates:
            - Query=hello,hi

        - id: product_route
          uri: lb://storeTemplate.product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://storeTemplate.coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: outGateway_route
          uri: lb://storeTemplate.outGateway
          predicates:
            - Path=/api/outGateway/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://storeTemplate.vip
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: inventory_route
          uri: lb://storeTemplate.inventory
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: storeTemplate_host_route
          uri: lb://storeTemplate.product
          predicates:
            - Host=storetemplate.com,item.storetemplate.com

        - id: storeTemplate_search_route
          uri: lb://storeTemplate.search
          predicates:
            - Host=search.storetemplate.com

        - id: storeTemplate_cart_route
          uri: lb://storeTemplate.cart
          predicates:
            - Host=cart.storetemplate.com

        - id: storeTemplate_order_route
          uri: lb://storeTemplate.order
          predicates:
            - Host=order.storetemplate.com

        - id: storeTemplate_auth_route
          uri: lb://storeTemplate.auth
          predicates:
            - Host=auth.storetemplate.com

  ## 前端项目，/api
## http://localhost:88/api/captcha.jpg   http://localhost:8080/renren-fast/captcha.jpg
## http://localhost:88/api/product/category/list/tree http://localhost:10000/product/category/list/tree
